### ISSUE TITLE
Version information  can contain characters instead of just 3 parts of numbers 

### ISSUE THREAD

**Issue by kienbui1995** [pbelskiy/quickbuild#10]
Please improve to support version with pattern: major.minor.patch[-qualifier]

**Comment by pbelskiy** [comment]
Hello! Could you give example of such version? And what is QB version is?

As example 8.0.x ?

**Comment by pbelskiy** [comment]
@kienbui1995 fixed in https://github.com/pbelskiy/quickbuild/releases/tag/v0.14.1
